version: "3.8"

services:
  melody-mood:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    container_name: "melody-mood"
    command: ["./melody-mood"]
    working_dir: /app
    ports:
      - "${APP_PORT}:${APP_PORT}"
